version: '3'

services:
    postgres:
        hostname: postgres
        container_name: pgsql-pkg
        image: postgres:9.6
        restart: unless-stopped
        volumes:
            - .docker/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: packagist
            POSTGRES_PASSWORD: 123456
        expose:
            - "5432"

    packagist:
        image: okvpn/packeton:latest
        container_name: packagist
        hostname: packagist
        restart: unless-stopped
        volumes:
            - .docker/redis:/var/lib/redis
            - .docker/zipball:/var/www/packagist/app/zipball
            - .docker/composer:/var/www/.composer
            - .docker/ssh:/var/www/.ssh
            - ${PWD}/PackagistWebBundle:/var/www/packagist/app/Resources/PackagistWebBundle
            - ${PWD}/Security:/var/www/packagist/app/Resources/FOSUserBundle/views/Security
            - ${PWD}/dist:/var/www/packagist/web/dist
        links:
            - "postgres"
        environment:
            PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
            PACKAGIST_DIST_HOST: https://pkg.okvpn.org
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_DRIVER: pdo_pgsql
            DATABASE_USER: postgres
            DATABASE_NAME: packagist
            DATABASE_PASSWORD: 123456
            ADMIN_USER: admin
            ADMIN_PASSWORD: composer
            ADMIN_EMAIL: admin@example.com
            TRUSTED_PROXIES: '172.16.0.0/12'
            PACKAGE_UPDATE_INTERVAL: 7200
            GITHUB_NO_API: 'true'

        ports:
            - 127.0.0.1:8088:80
