version: '3'

services:
    packagist:
        image: packeton/packeton:latest
        container_name: packagist
        hostname: packagist
        restart: unless-stopped
        volumes:
            - .docker:/data
            - ${PWD}/Security/login.html.twig:/var/www/packagist/templates/user/login.html.twig
            - ${PWD}/Security/layout.html.twig:/var/www/packagist/templates/layout.html.twig
        environment:
            ADMIN_USER: admin
            ADMIN_PASSWORD: 123456
            ADMIN_EMAIL: admin@example.com

        ports:
            - "127.0.0.1:8088:80"
